version: "3"

services:
  app:
    image: memgraph/memgraph-slack-app
    build: .
    depends_on:
      - kafka
      - memgraph
    environment:
      - KAFKA_TOPIC=slack-events
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9094
      - MEMGRAPH_HOST=memgraph
      - MEMGRAPH_PORT=7687

  zookeeper:
    image: bitnami/zookeeper:3.7
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181

  kafka:
    image: bitnami/kafka:2
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9093:9093
      - 9094:9094
    environment:
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=OUT_IN_HOST://localhost:9092,OUT_IN_DOCKER://host.docker.internal:9093,IN_COMPOSE://kafka:9094
      - KAFKA_CFG_LISTENERS=OUT_IN_HOST://:9092,OUT_IN_DOCKER://:9093,IN_COMPOSE://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=OUT_IN_HOST:PLAINTEXT,OUT_IN_DOCKER:PLAINTEXT,IN_COMPOSE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=IN_COMPOSE
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  memgraph:
    image: memgraph/memgraph-nlp
    build: memgraph
    entrypoint:
      - "/usr/lib/memgraph/memgraph"
      - "--kafka-bootstrap-servers=kafka:9094"
    ports:
      - 7687:7687
    depends_on:
      - kafka
